


mysql:
  instance:
    server-url:
      jdbc:mysql://localhost:3306/onemetaworld?useSSL=NO
    driver:
      com.mysql.cj.jdbc.Driver
    username:
      root
    password:
      hugeman1

server:
  port:
    8082